CREATE TABLE "ATG_4076_SALE_REGION"(
 "SalesID" CHAR(2) NOT NULL ,
 "Region" INTEGER NOT NULL ,
 PRIMARY KEY ("SalesID", "Region")
);
CREATE UNIQUE INDEX "key0" ON "ATG_4076_SALE_REGION"("SalesID", "Region"); 